services:
  gitea:
    image: gitea/gitea:1.23-nightly
    environment:
      - USER_UID=1000
      - USER_GID=1000
      # https://docs.gitea.com/administration/config-cheat-sheet
      - GITEA__database__DB_TYPE=postgres
      - GITEA__database__HOST=gitea_db:5432
      - GITEA__database__NAME=gitea
      - GITEA__database__USER=gitea
      - GITEA__database__PASSWD=gitea
      - GITEA__server__ROOT_URL=${GITEA_ROOT_URL:-http://localhost:3000/}
      - GITEA__security__INSTALL_LOCK=true
      # - GITEA__security__SECRET_KEY=${GITEA_SECRET_KEY:-}
      - GITEA__service__DISABLE_REGISTRATION=true # 登録を非表示にし管理者しか登録できなくする
      # - GITEA__service__REQUIRE_SIGNIN_VIEW=true # ログインを必須にする
      # - GITEA__service__ALLOW_ONLY_INTERNAL_REGISTRATION=true
      # - GITEA__openid__ENABLE_OPENID_SIGNIN=false
    volumes:
      - gitea_data:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "${GITEA_WEB_PORT:-3000}:3000"
      - "${GITEA_SSH_PORT:-2222}:22"
    depends_on:
      - gitea_db
    restart: unless-stopped

  gitea_db:
    image: postgres:15
    environment:
      - POSTGRES_USER=gitea
      - POSTGRES_PASSWORD=gitea
      - POSTGRES_DB=gitea
    volumes:
      - gitea_db_data:/var/lib/postgresql/data
    restart: unless-stopped

  gitea_act_runner:
    image: gitea/act_runner:0.2.11
    environment:
      GITEA_INSTANCE_URL: "http://gitea:3000/"
      GITEA_RUNNER_REGISTRATION_TOKEN: "${GITEA_RUNNER_REGISTRATION_TOKEN:-dummy}"
      GITEA_RUNNER_NAME: "gitea_act_runner"
    volumes:
      - gitea_act_runner_data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped

volumes:
  gitea_data:
  gitea_db_data:
  gitea_act_runner_data:
